name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    prepare:
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

    update:
        - name: Pull the project
          run: git pull

    cleaninstall:
        steps:
            - name: Install dependencies
              run: npm i

            - name: Clean files
              run: |
                  rm -Rf .env
                  rm -Rf build

    envfile:
        - name: Create the .env file
          run: |
              touch .env
              echo REACT_APP_SOCKET_URL="wss://www.chattyroom.ovh" >> .env
              echo REACT_APP_SERVER_URL="https://www.chattyroom.ovh/api" >> .env
              cat .env

    build:
        - name: Build the project
          run: npm run build
