name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env: 
    REACT_APP_SOCKET_URL: https://chattyroom.ovh
    REACT_APP_SERVER_URL: https://chattyroom.ovh

jobs:
    deploy:
        name: Update
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Pull the project
              run: git pull

            - name: Install dependencies
              run: npm i

            - name: Build the app
              run: npm run build
