name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env: 
    REACT_APP_SOCKET_URL: wss://51.91.79.44:3001
    REACT_APP_SERVER_URL: https://51.91.79.44:3001

jobs:
    deploy:
        name: Update
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Pull the project
              run: git pull

            - name: Clean files / install dependencies / create .env and build
              run: |
                  rm -Rf .env
                  rm -Rf build
                  npm i
                  npm run build
